image: python:3.5

before_script:
  - export COVERAGE="true"
  - apt-get update -qq && apt-get install -y -qq libgl1-mesa-glx
  - source build_tools/install.sh

test:
  script:
    - source build_tools/execute.sh
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master